name: Build the app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/*
      - ng-github-actions/*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        shell: bash
        working-directory: ng-github-actions
      - run: npm run lint
        shell: bash
        working-directory: ng-github-actions
      - run: npm run test:ci
        shell: bash
        working-directory: ng-github-actions
      - run: npm run build
        shell: bash
        working-directory: ng-github-actions