name: Build the app
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/*
      - ng-github-actions/*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: tree
        shell: bash
      - run: npm install
        working-directory: ng-github-actions
      - run: npm run build
        working-directory: ng-github-actions
